second commit
Fahnenfluchtige/MusicApp pull request #1
Opened 2023-10-10 17:35 UTC by Fahnenfluchtige

2023-11-11 14:11 UTC, kirill-stupakov requested changes

2023-11-11 14:11 UTC, kirill-stupakov commented on Dockerfile
> +RUN npm install
При деплое рекомендуется использовать [npm clean-install](https://docs.npmjs.com/cli/v8/commands/npm-ci)

2023-11-11 14:11 UTC, kirill-stupakov commented on Dockerfile
> +CMD ["npm", "run", "dev"]
Также при деплое не рекомендуется использовать dev-сервер )))

Лучше будет сначала сбилдить production сборку, потом уже её раздавать без дев сервера (например с помощью пакета [serve](https://www.npmjs.com/package/serve))

```dockerfile
ENV NODE_ENV=production

RUN npm install -g serve

RUN npm ci

RUN npm run build

EXPOSE 3000

CMD ["npm", "run", "serve"]
```

Где `npm run serve` --- твой кастомный скрипт, который добавляется в `package.json` и выглядит как-то так
```JSON
{
  ...
  "scripts": {
    ...
    "serve": "serve -s dist -p 3000"
  },
}
```

2023-11-11 14:11 UTC, kirill-stupakov commented on package.json
> +    "build-storybook": "storybook build"
а зачем сторибук?

2023-11-11 14:11 UTC, kirill-stupakov commented on src/App.tsx
> +function App() {
Между импортами и объявлением компонента принято пустую строчку оставлять

2023-11-11 14:11 UTC, kirill-stupakov commented on src/App.tsx
> +
А тут две пустые строчки не нужны

2023-11-11 14:11 UTC, kirill-stupakov commented on vite.config.ts
> +    port: 5173, // you can replace this port with any port
Это всё по идее не нужно будет, если раздавать внутри докера сбилженную статику

2023-11-11 14:11 UTC, kirill-stupakov commented on tasks.txt
Список того, что сделано, лучше указывать в описании ПРа и использовать markdown:

```markdown
* [x] сделано то
* [ ] не сделано это
* [ ] частично сделано
* * [x] q
* * [x] w
* * [ ] e
```

* [x] сделано то
* [ ] не сделано это
* [ ] частично сделано
* * [x] q
* * [x] w
* * [ ] e

2023-11-11 14:11 UTC, kirill-stupakov commented on src/components/Controls.tsx
> +  playing: boolean;
isPlaying

2023-11-11 14:11 UTC, kirill-stupakov commented on src/components/Controls.tsx
> +  loop: boolean;
не используется

2023-11-11 14:11 UTC, kirill-stupakov commented on src/components/Controls.tsx
> +  prevSong: () => void;
`handlePlay` и `handlePause` можно заменить на `togglePause` по аналогии с `toggleLoop`. А иконку на кнопке будешь всё так же отрисовывать в зависимости от `isPlaying`

И ещё нейминг: `onShuffle` (или даже `toggleShuffle`), `onPlayNextSong`

2023-11-11 14:11 UTC, kirill-stupakov commented on src/components/Controls.tsx
> +  playSong: (index: number) => void;
не используется

2023-11-11 14:11 UTC, kirill-stupakov commented on src/components/Controls.tsx
> +  }, [progress, seeking]);
ничего нипанимаю :(

Во-первых [useMemo](https://react.dev/reference/react/useMemo) нужен для того, чтобы мемоизировать какое-то значение между рендерами, и соответственно это значение должно чему-то присваиваться:
```ts
const memoizedValue = useMemo(() => someTimeConsumingStuff(a, b), [a, b]);
```
В данном же случае тебе надо, чтобы какая-то функция выполнялась при изменении стейта/пропсов, для этого есть [useEffect ](https://react.dev/reference/react/useEffect)

Во-вторых не понятно что такое `seeking` без `setSeeking` и `setPlayed` без `played`

2023-11-11 14:11 UTC, kirill-stupakov commented on src/components/Controls.tsx
> +      </button>
`toggleLoop` и сконкой shuffle

2023-11-11 14:11 UTC, kirill-stupakov commented on src/components/Controls.tsx
> +      </button>
и `toggleShuffle` с иконкой loop

2023-11-11 14:11 UTC, kirill-stupakov commented on src/components/Controls.tsx
> +      <button onClick={() => prevSong()}>
`onClick={prevSong}`

2023-11-11 14:11 UTC, kirill-stupakov commented on src/components/Duration.tsx
> +export const Duration = ({ seconds }: { seconds: number }) => {
лучше всегда создавать тип для пропсов

2023-11-11 14:11 UTC, kirill-stupakov commented on src/components/Duration.tsx
> +    <time className="time">
В [time](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/time) нужно передавать атрибут `datetime`, который ещё и должен иметь специальнй формат, иначе от этого тега никакого толку не будет :)

Предлагаю тебе с этим не париться и сделать div просто

2023-11-11 14:11 UTC, kirill-stupakov commented on src/components/Duration.tsx
> +};
уже [есть](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String/padStart) такая функция

2023-11-11 14:11 UTC, kirill-stupakov commented on src/components/DurationBar.tsx
> +import ReactPlayer from "react-player";
Импорт сторонних библиотек лучше сверху писать

2023-11-11 14:11 UTC, kirill-stupakov commented on src/components/DurationBar.tsx
> +  };
?

2023-11-11 14:11 UTC, kirill-stupakov commented on src/components/DurationBar.tsx
> +  playing: boolean;
не используется

2023-11-11 14:11 UTC, kirill-stupakov commented on src/components/DurationBar.tsx
> +  loop: boolean;
не используется

2023-11-11 14:11 UTC, kirill-stupakov commented on src/components/DurationBar.tsx
> +  const [seeking, setSeeking] = useState<boolean>(false);
internalProgress,  isSeeking

2023-11-11 14:11 UTC, kirill-stupakov commented on src/components/DurationBar.tsx
> +  useMemo(() => {
useEffect

2023-11-11 14:11 UTC, kirill-stupakov commented on src/components/DurationBar.tsx
> +  }, [progress, seeking]);
Вроде упростить можно

```ts
if (!seeking) {
  setPlayed(progress);
}
```

2023-11-11 14:11 UTC, kirill-stupakov commented on src/components/DurationBar.tsx
> +      <div>{<Duration seconds={duration * played} />}</div>
А зачем Duration в фигурных скобках?

2023-11-11 14:11 UTC, kirill-stupakov commented on src/components/DurationBar.tsx
> +        -{<Duration seconds={duration * (1 - played)} />}
тот же вопрос

2023-11-11 14:11 UTC, kirill-stupakov commented on src/components/Main.tsx
> +  is_verified: boolean;
`isVerified`

2023-11-11 14:11 UTC, kirill-stupakov commented on src/components/Navigation.tsx
> +      <menu className="area-menu">
`<menu>` это [список](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/menu), соответственно и разметка должна быть с `<li>`

2023-11-11 14:11 UTC, kirill-stupakov commented on src/components/Player.tsx
> +  };
чтобы не вызывать `handlePlay` в каждой функции, можно воспользоваться `useEffect`-ом:

```TS
useEffect(() => {
  handlePlay();
}, [currentSongIndex]);
```

2023-11-11 14:11 UTC, kirill-stupakov commented on src/components/Player.tsx
> +    handlePlay();
А почему включение за-loop-ливания (извини, не удержался) должно начинать воспроизведение?

2023-11-11 14:11 UTC, kirill-stupakov commented on src/components/SongsList.tsx
> +  const [activeSongIndex, setActiveSongIndex] = useState(-1);
этот стейт уже есть в компоненте Player

2023-11-11 14:11 UTC, kirill-stupakov commented on src/components/SongsList.tsx
> +  const SetActive = (index: number) => {
`setActive`

2023-11-11 14:11 UTC, kirill-stupakov commented on src/components/SongsList.tsx
> +                activeSongIndex === song.id - 1 ? "active-song" : "columns"
может тогда сделать стейт `activeSongId` ?

2023-11-11 14:11 UTC, kirill-stupakov commented on src/components/SongsList.tsx
> +                  style={{ width: "2rem", height: "2rem" }}
инлайн стили

2023-11-11 14:11 UTC, kirill-stupakov commented on src/index.css
> +}
?

2023-11-11 14:11 UTC, kirill-stupakov commented on src/styles/Controls.css
> +  grid-template-columns: repeat(auto-fill, minmax(200px, 1fr));
а зачем тут свойство для грида? `display: flex` же стоит

2023-11-11 14:11 UTC, kirill-stupakov commented on src/styles/Player.css
> +    rgba(38, 38, 38, 0.75) 100%
в данном случае проценты можно убрать

2023-11-11 14:11 UTC, kirill-stupakov commented on src/styles/Searchbar.css
> +  outline: none !important;
а без important не работает?

2023-11-11 14:22 UTC, Fahnenfluchtige commented on package.json
> +    "build-storybook": "storybook build"
Не нужен, просто был в тасках записал, решила опробовать, что за штука
Уберу

2023-11-11 14:33 UTC, Fahnenfluchtige commented on src/components/Controls.tsx
> +  }, [progress, seeking]);
насчет стейтов -- убрала неиспользуемые переменные, тк eslint на них ругался. вроде eslint отключила, а переменные вернуть забыла
useMemo - да, поняла, не совсем корректен в данном случае. это был ctrl+c ctrl+v из какого-то тутора)

2023-11-11 14:35 UTC, Fahnenfluchtige commented on src/components/DurationBar.tsx
> +  };
забыла удалить ненужную функцию

2023-11-11 14:37 UTC, kirill-stupakov commented on src/components/Controls.tsx
> +  }, [progress, seeking]);
А зачем здесь вообще эти стейты нужны, если ты один присваиваешь, но не читаешь, а второй читаешь, но не присваиваешь?)

2023-11-11 14:37 UTC, kirill-stupakov commented on src/components/DurationBar.tsx
> +  };
а почему ненужную? тебе ж надо отслеживать когда сикинг начался?

2023-11-11 14:38 UTC, Fahnenfluchtige commented on src/components/Player.tsx
> +    handlePlay();
А, ты прав... Не совсем хорошо, особенно, когда переключение произошло посередине проигрывания

2023-11-11 14:41 UTC, Fahnenfluchtige commented on src/styles/Controls.css
> +  grid-template-columns: repeat(auto-fill, minmax(200px, 1fr));
изначально был грид, забыла убрать

2023-11-11 14:43 UTC, Fahnenfluchtige commented on src/styles/Searchbar.css
> +  outline: none !important;
по крайней мере, лишни не было) работает

2023-11-11 14:57 UTC, Fahnenfluchtige commented on src/components/DurationBar.tsx
> +  };
вроде как скачки в value происходили из-за нее (проверила -- нет, не по этой причине). но да, справедливо

2023-11-11 15:00 UTC, Fahnenfluchtige commented on src/components/Controls.tsx
> +  }, [progress, seeking]);
убрала)

2023-11-13 09:24 UTC, merged

2023-11-13 09:32 UTC, kirill-stupakov approved these changes
Есть ещё некоторые моменты, но для начала норм